#!/usr/bin/env bash

function run_step() {
  local fn="$1"
  "$fn" || echo "$fn failed"
}

github="https://github.com"

function bs_install_essentials() {
  local essentials=(git stow base-devel cmake zsh nvim)
  echo "Essentials: ${essentials[@]}"

  sudo pacman -S --needed "${essentials[@]}"
}

function bs_install_dotfiles() {
  local repo="$github/RodrigoAroeira/.dotfiles"
  (
    cd || exit 1
    if [ -d ".dotfiles" ]; then
      echo "Dotfiles already installed, skipping..."
      exit 1
    fi
    git clone "$repo" --recurse-submodules || exit 1
    cd .dotfiles
    stow . --adopt
    git restore .
  )
}

fns=()
case "${1:-all}" in
essentials) fns+=(bs_install_essentials) ;;
dotfiles) fns+=(bs_install_dotfiles) ;;
all)
  fns=($(declare -F | awk '{print $3}' | grep '^bs_'))
  ;;
*)
  (
    echo "Unknown option $1"
    echo "Usage: $0 [essentials|dotfiles|all]"
  ) >&2
  exit 1
  ;;
esac

for fn in ${fns[@]}; do
  run_step "$fn"
done
