#!/usr/bin/env bash

function run_step() {
  local fn="$1"
  "$fn" || echo "$fn failed"
}

github="https://github.com"

function bs_install_essentials() {
  local essentials=(git stow base-devel cmake zsh nvim)
  echo "Essentials: ${essentials[@]}"

  sudo pacman -S --needed "${essentials[@]}"
}

function bs_install_dotfiles() {
  local repo="$github/RodrigoAroeira/.dotfiles"
  (
    cd || exit 1
    if [ -d ".dotfiles" ]; then
      echo "Dotfiles already installed, skipping..."
      exit 1
    fi
    git clone "$repo" --recurse-submodules || exit 1
    cd .dotfiles
    stow . --adopt
    git restore .
  )
}

function bs_install_yay() {
  local repo="https://aur.archlinux.org/yay.git"
  (
    cd /tmp
    git clone "$repo"
    cd yay
    makepkg -sir
    cd ..
    rm -rf yay
  )
}

function bs_install_omz() {
  (
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  )
}

selection="$1"
options=($(declare -F | awk '{print $3}' | grep '^bs_install_' | sed 's/^bs_install_//'))

if [[ "$selection" != "all" ]] && ! [[ " ${options[*]} " =~ " $selection " ]]; then
  (
    echo "Unknown option: $selection"
    formatted=$(echo "${options[*]}" | sed 's/ /\|/g')
    echo "Usage: $0 [$formatted|all]"
  ) >&2
  exit 1
fi

if [[ "$selection" == "all" ]]; then
  fns=($(declare -F | awk '{print $3}' | grep '^bs_install_'))
else
  fns=("bs_install_$selection")
fi

for fn in "${fns[@]}"; do
  run_step "$fn"
done
